name: Linting

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install deps
        run: |
          pip install sphinx-lint ruff==0.8.5
      - name: ruff
        run: |
          ruff check src/elli tests
      - name: ruff formatting
        run: |
          ruff format --check src/elli tests
      - name: Run Sphinx Linting
        run: |
          sphinx-lint .
