name: Dev requirements for target python

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install package (no deps)
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv pip install --system --no-deps .[fitting,dev]
          uv pip install --system torch --index-url https://download.pytorch.org/whl/cpu
      - name: Install dev requirements
        run: |
          uv pip install --system -r requirements/dev-requirements.txt
      - name: Test with pytest
        run: |
          pytest --nbmake
